### ISSUE TITLE
About the Domain adaptive understanding of the paper

### ISSUE THREAD

**Issue by gaowq2017** [lhoyer/HRDA#10]
Thanks for sharing the code. I have some confusion when reading the paper as follow:
1、The paper using context crop、detail crop and weighted attention to improve the segmentation accuraccy but how to transform it to domian adaptive? Only Self_training as like DAFormer? or others?
2、Inference with overlapping sliding window that using random crops or one by one crops?
Thank you very much

**Comment by lhoyer** [comment]
Thank you for your interest in our work. 
1. The advantage of HRDA is that it can be combined with different UDA methods. So, it works both with adversarial training as well as self training for domain adaptation. Please, have a look at Tab. 2 and the corresponding discussion in the text for more details. 
2. The inference with overlapping sliding crops is done systematically and not randomly.
