### ISSUE TITLE
Evaluation on ACDC 

### ISSUE THREAD

**Issue by SnowdenLee** [lhoyer/HRDA#12]
Hi, 
did you also have any evaluation on ACDC dataset?

**Comment by lhoyer** [comment]
Hi,
Currently, there is no evaluation on Cityscapes-to-ACDC. However, I'm working on it. I'll let you know as soon as the results are ready.

**Comment by lhoyer** [comment]
I have added the code for Cityscapes-to-ACDC and Cityscapes-to-DarkZurich to this repo. The results are provided in the README.md. It shows that HRDA also performs very well for clean to adverse weather and day-to-nighttime adaptation.

**Comment by SnowdenLee** [comment]
Thank you!
