### ISSUE TITLE
trainsform to MRI

### ISSUE THREAD

**Issue by cc1609130201** [lhoyer/HRDA#13]
Hi!
Can this model be used for tumor segmentation? if answer is yes，where we can be modified to fit this task?

**Comment by lhoyer** [comment]
Hi,
Technically, HRDA can probably also be applied to tumor segmentation. For that purpose, you need to change the data loaders. You can have a look at https://github.com/lhoyer/HRDA/blob/master/configs/_base_/datasets/uda_gtaHR_to_cityscapesHR_1024x1024.py and https://github.com/lhoyer/HRDA/blob/master/mmseg/datasets/gta.py as a starting point.
