### ISSUE TITLE
how long to train the model. If this code can run on 3090

### ISSUE THREAD

**Issue by yuheyuan** [lhoyer/HRDA#14]
I am interested in this paper and I knwo transform framwork needs high equipment.
So I want to know the time to train it.
My device is not good. So I want to ask.

**Comment by lhoyer** [comment]
You can find the runtime details in Section G in the appendix on arXiv. Training DAFormer takes 16 hours on a single Nivida RTX 2080 Ti. As you have a more powerful RTX 3090, it should be faster on your device.

**Comment by lhoyer** [comment]
Training HRDA takes 32 hours on a single Nvidia Titan RTX and requires 22.5 GB GPU memory. Further details can be found in Tab. 5 and Sec. F.
