### ISSUE TITLE
 CUDA out of memory. how to change GPU, I want to specify a GPU device

### ISSUE THREAD

**Issue by yuheyuan** [lhoyer/HRDA#15]
```txt
RuntimeError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 0; 23.70 GiB total capacity; 1.33 GiB already allocated; 5.00 MiB free; 1.40 GiB reserved in total by PyTorch)
```
When I run daformer,It's Ok.
But , I run HRDA, it occour CUDA out of memory.
I want to change GPU 0 to GPU 1
But I don't know how to change it.
Usually, I use code to specify GPU by code
```python
import os
os.environ["CUDA_VISIBLE_DEVICES"] = '1'
```
But it dosen't work in this work.
I find code in your gtaHR2csHR_hrda.py
```python
n_gpus = 1
gpu_model = 'NVIDIATITANRTX'
```
is this gpu_model should change?
My gpus are two 3090.
So I want to know how to change GPU in this code. defualt is GPU 0
Or how to change configs to make the code successfully.

Maybe GPU 1 is used, I specify GPU 1,  but in pytorch the index of GPU 1 become GPU 0.Then it occour this problem.

So, I want to know if 3090 can run this code. Or change the configs to make this run.

**Comment by lhoyer** [comment]
The flags `n_gpus` and `gpu_model` are for internal purposes only and have no functionality in this repository. I forgot to remove them.

However, you can specify the GPU by setting `cfg['gpu_ids']`.

**Comment by HKQX** [comment]
You can modify the apis\train.py file     as follows
![image](https://user-images.githubusercontent.com/50910351/201027856-f2312e26-64e0-4383-bdfe-498a998f1f56.png)
