### ISSUE TITLE
The performance of DAFormer in this repo.

### ISSUE THREAD

**Issue by luyvlei** [lhoyer/HRDA#17]
I tried training the DAFormer configuration and got 66.1 mIoU, slightly lower than the DAFormer reported. Is the DAFormer in this repository consistent with the original author's code. Or it could be due to a different version of CUDA. I used CUDA 10.2 due to my graphics driver version.

**Comment by lhoyer** [comment]
I was able to reproduce the DAFormer results (averaged over three random seeds) also with this repository. It might be that different software library versions have an influence on the performance. The implementation of DAFormer in this repository is the same as in the original DAFormer repository.

**Comment by luyvlei** [comment]
Thanks, I will change CUDA version and try again
