### ISSUE TITLE
Questions on Sliding Window Inference

### ISSUE THREAD

**Issue by JoinWorldMC** [lhoyer/HRDA#18]
In the appendix, 'whole' [2] does not use sliding window inference.
So, what does [1] mean?

`[1] hr_slide_inference = False`
`[2] test_cfg=dict(mode='whole')`

**Comment by lhoyer** [comment]
HRDA typically uses two levels of cropping during training. The outer crop is used to capture LR context while the inner crop is used to capture HR details. [2] means that the whole image is used as the outer crop during inference, while [1] means that the whole outer crop is used as the inner crop during inference.
