### ISSUE TITLE
Questions on Feature Distance

### ISSUE THREAD

**Issue by HuayuWong** [lhoyer/HRDA#19]
Dear Lucas,

I am interested in your recent great work HRDA and thanks for sharing your code. During reading it I have some questions about the module of feature distance. [HRDA/mmseg/models/uda/dacs.py]

<img width="705" alt="image" src="https://user-images.githubusercontent.com/30103387/191608704-bb06924b-d263-4a41-8114-62e01db7bc62.png">

From the Figure it can be seen that features from multiple input scales are used only when  feature_scale in feature_scale_all_strs. However according to your provided config file, feature_scale = 0.5 while feature_scale_all_strs = ['all'], thus this module will never be executed.

So are the features from multiple input scales not used during the training process?

**Comment by lhoyer** [comment]
Thank you for your interest in our work! Yes, you are right. The feature distance is only calculated for features of the input scale 0.5.

**Comment by HuayuWong** [comment]
Got it : )
