### ISSUE TITLE
Regarding code usability on colab

### ISSUE THREAD

**Issue by sparshgarg23** [lhoyer/HRDA#2]
Hello,
I am highly interested in applications of domain adaptation in semantic segmentation,and I came across your work.
I have some questions regarding the requirements
My current colab environment requirments is as follows
```
 Torch1.11.0+cu113 True
Cuda 11.1
compiler GCC 7.3
 MMCV1.5.0
 MMSegmentation 0.24.1
```
Since my torch ,cuda ,mmcv and mmsegmentation are higher than the ones recommended in the readme and requirments.txt,should I downgrade them or is there no need for any downgrading.

**Comment by lhoyer** [comment]
Thanks for your interest in our work!
In order to have the same library interface and ensure reproducibility, I would recommend that you create a new environment and set it up as described in the README.md.

Best,
Lukas
