### ISSUE TITLE
Question about the inference phase

### ISSUE THREAD

**Issue by JoinWorldMC** [lhoyer/HRDA#21]
I have calculated the necessary parameters in the inference phase. Is my calculation correct?

**Case1.** 
If not using sliding window LR context crop, config is as follows:
`[1]test_cfg=dict(mode='whole'))`
If not using sliding window HR detail crop, config is as follows:
`[2]hr_slide_inference=False,`

1. The encoder is forwarded only once per image.
2. According to [1], the LR context crop image(whole image) is forwarded to the decoder once.
3. According to [2], the HR detail crop image(whole image) is forwarded to the decoder once.

**Q1. if the model parameter is 80M(encoder:60M, decoder20M), the parameter required to forward one image is 100M(60M + 20M(LR crop) + 20M(HR crop). Is that right?**

**Case2.** 
If not using sliding window LR context crop, config is as follows:
`[1]test_cfg=dict(mode='whole'))`
If using sliding window HR detail crop, config is as follows:
`[2]hr_slide_inference=True,`

1. The encoder is forwarded only once per image.
2. According to [1], the LR context crop image(whole image) is forwarded to the decoder once.
3. According to [2], the HR detail crop image is forwarded to the decoder as much as the slide size(N).

**Q2. if the model parameter is 80M(encoder:60M, decoder20M), the parameter required to forward one image is 60M + 20M(LR crop) + 20M x N(HR crop). Is that right?**

**Comment by lhoyer** [comment]
Hi @JoinWorldMC,

As the encoder and decoder parameters are shared for all LR and HR crops, the number of model parameters is independent of the inference procedure.

Assuming that you were interested in the computation complexity of the inference instead of the number of parameters, I will comment on that: The number of forward passes of the decoder is described correctly in the case description. However, the encoder is not only forwarded once per image but once for each crop, which is the same number as decoder forward passes. Also, if you want to estimate the computation complexity, you also need to consider that the input size is larger when forwarding the whole image instead of a crop.

Best,
Lukas

**Comment by JoinWorldMC** [comment]
@lhoyer 
Appreciate your kindness.
You're right. What I want to know is the forward pass.

Can you cross check if the calculation is correct?

In case 1, The number of forward passes is 160M
*160M = 60M(Encoder(LR Crop)) + 20M(Decoder(LR Crop)) + 60M(Encoder(HR Crop)) + 20M(Decoder(HR crop))

Because if hr_slide_inference and sliding window inference are not used, the whole image is used for LR context crop and HR detail crop.

**Comment by JoinWorldMC** [comment]
@lhoyer 
Also, am I wrong to think that HRDA is a resolution-based ensemble method?

**Comment by lhoyer** [comment]
> @lhoyer Appreciate your kindness. You're right. What I want to know is the forward pass.
> 
> Can you cross check if the calculation is correct?
> 
> In case 1, The number of forward passes is 160M *160M = 60M(Encoder(LR Crop)) + 20M(Decoder(LR Crop)) + 60M(Encoder(HR Crop)) + 20M(Decoder(HR crop))
> 
> Because if hr_slide_inference and sliding window inference are not used, the whole image is used for LR context crop and HR detail crop.

What do you mean with "number of forward passes"? I would say that there there is one forward pass of the encoder and decoder for the LR crop and one forward pass of the encoder and decoder for the HR crop in case 1.

**Comment by lhoyer** [comment]
> @lhoyer Also, am I wrong to think that HRDA is a resolution-based ensemble method?

HRDA is not strictly an ensemble method as there is only one model trained.

**Comment by JoinWorldMC** [comment]
@lhoyer 

In the paper. Figure 2(b) includes "Reassemble".

What I mean by forward pass is whether or not **Reassemble** is performed only once.
That is, parts of the image should not be inferred multiple times.

In Case 1, does **Reassemble** work once?

**Comment by JoinWorldMC** [comment]
@lhoyer 

> > @lhoyer Also, am I wrong to think that HRDA is a resolution-based ensemble method?
> 
> HRDA is not strictly an ensemble method as there is only one model trained.

HRDA is not an ensemble because there is only one model, but it looks similar to Test Time Adaptation. Isn't it?

**Comment by lhoyer** [comment]
> @lhoyer
> 
> In the paper. Figure 2(b) includes "Reassemble".
> 
> What I mean by forward pass is whether or not **Reassemble** is performed only once. That is, parts of the image should not be inferred multiple times.
> 
> In Case 1, does **Reassemble** work once?

In case 1, there is no sliding window inference with the detail crop. Therefore, there is no reassembly necessary. Instead, the whole HR crop in the context crop area (larger than the detail crop) is forwarded once through the network.

**Comment by lhoyer** [comment]
> @lhoyer
> 
> > > @lhoyer Also, am I wrong to think that HRDA is a resolution-based ensemble method?
> > 
> > 
> > HRDA is not strictly an ensemble method as there is only one model trained.
> 
> HRDA is not an ensemble because there is only one model, but it looks similar to Test Time Adaptation. Isn't it?

As Test Time Adaptation is a certain domain adaptation setting, which can be approached with different methods, I don't know to which specific method you are referring when comparing it with HRDA. Generally, HRDA is not a Test Time Adaptation method as the source data is required for the domain adaptation process.
