### ISSUE TITLE
Some issue

### ISSUE THREAD

**Issue by LuPaoPao** [lhoyer/HRDA#24]
XIO:  fatal IO error 25 (Inappropriate ioctl for device) on X server "localhost:12.0"
      after 387 requests (387 known processed) with 4 events remaining.

**Comment by lhoyer** [comment]
You probably need to switch your matplotlib backend: https://stackoverflow.com/questions/45993879/matplot-lib-fatal-io-error-25-inappropriate-ioctl-for-device-on-x-server-loc

**Comment by LuPaoPao** [comment]
Thanks a lot~
