### ISSUE TITLE
Software to make the demo

### ISSUE THREAD

**Issue by June01** [lhoyer/HRDA#25]
Hi, thanks for the nice work, while the demo is quite impressive. I am wondering could you please share the way you make the demo? Any response is appreciated.

**Comment by lhoyer** [comment]
Hi @June01, 
Thanks for your interest in our work! I have attached the jupyter notebook that I have used to generate the slider. I had to change the extension to .txt to upload it here. Please, change it back to .ipynb after the download.

[PredictionSlideDemoPublic.txt](https://github.com/lhoyer/HRDA/files/9945525/PredictionSlideDemoPublic.txt)
