### ISSUE TITLE
Using mixed precision during the training process.

### ISSUE THREAD

**Issue by Caillen-W** [lhoyer/HRDA#28]
I used a single RTX 3090 to run the codes, but I got the error about the cuda out of memory. So that I want to run the codes using mixed precision. Where should I modify the codes to use the mixed precision during the training process. Thank you very much.

**Comment by lhoyer** [comment]
This repository is based on mmsegmentation v0.16.0, which supports mixed precision training according to its README.md (https://github.com/open-mmlab/mmsegmentation/tree/v0.16.0). However, the HRDA was not developed considering this aspect. So, you have to check if the relevant changes compared to the basic mmsegmentation framework are compatible with mixed precision training. Also, from experience with a previous project, mixed precision training can cause training instabilities and the original results might be not reproducable.

**Comment by lhoyer** [comment]
To reduce GPU memory consumption, you can try to share the backward pass of source and FD loss:

```python
# Train on source images
clean_losses = self.get_model().forward_train(
    img, img_metas, gt_semantic_seg)
seg_debug['Source'] = self.get_model().decode_head.debug_output
clean_loss, clean_log_vars = self._parse_losses(clean_losses)
log_vars.update(clean_log_vars)

# ImageNet feature distance
if self.enable_fdist:
    feat_loss, feat_log = self.calc_feat_dist(img, gt_semantic_seg, src_feat)
    log_vars.update(add_prefix(feat_log, 'src'))
    clean_loss = clean_loss + feat_loss

# Shared source backward
clean_loss.backward()
del clean_loss
if self.enable_fdist:
    del feat_loss
```

**Comment by kaigelee** [comment]
> To reduce GPU memory consumption, you can try to share the backward pass of source and FD loss:
> 
> ```python
> # Train on source images
> clean_losses = self.get_model().forward_train(
>     img, img_metas, gt_semantic_seg)
> seg_debug['Source'] = self.get_model().decode_head.debug_output
> clean_loss, clean_log_vars = self._parse_losses(clean_losses)
> log_vars.update(clean_log_vars)
> 
> # ImageNet feature distance
> if self.enable_fdist:
>     feat_loss, feat_log = self.calc_feat_dist(img, gt_semantic_seg, src_feat)
>     log_vars.update(add_prefix(feat_log, 'src'))
>     clean_loss = clean_loss + feat_loss
> 
> # Shared source backward
> clean_loss.backward()
> del clean_loss
> if self.enable_fdist:
>     del feat_loss
> ```

I wonder if this way will hurt the performance?

**Comment by lhoyer** [comment]
From my experience, it did not significantly affect the performance.

**Comment by kaigelee** [comment]
> From my experience, it did not significantly affect the performance.

Thank you for your reply. In fact, I'm using torch.utils.checkpoint to save GPU consumption. When running HRDA, it only requires 20G of memory, but will increase training time.
