### ISSUE TITLE
Code to make the heatmap

### ISSUE THREAD

**Issue by xiaoachen98** [lhoyer/HRDA#29]
Hi, I'm enjoying your excellent work! Could you please provide the code for the heatmap of Figure. 5? Thanks a lot!

**Comment by lhoyer** [comment]
Thanks a lot! 
Assuming that you have a pandas data frame `plot_df` with the relevant IoUs, you can visualize it using:

```python
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

plot_df = plot_df.set_index('name')
comp_df = plot_df - plot_df.loc[baseline, :]

fig = plt.figure(figsize=(16, 3))
g = sns.heatmap(
    comp_df, cmap='RdBu_r', center=0, annot=plot_df, fmt='.1f, cbar=False)
g.tick_params(left=False, bottom=False)
g.set_ylabel('')
g.set_yticklabels(g.get_yticklabels(), rotation=0)
g.set_xticklabels(g.get_xticklabels(), rotation=90)
```

`baseline` is the name of the row that contains the values, which will be colored white.

**Comment by xiaoachen98** [comment]
> 

Tanks very much!!
