### ISSUE TITLE
Using 2 GPUs to train the model.

### ISSUE THREAD

**Issue by Caillen-W** [lhoyer/HRDA#30]
I want to know if I use 2 GPUs to train the model, where I should modify in the codes. Thank you very much.

**Comment by lhoyer** [comment]
Thank you for your interest in HRDA. Multi-GPU training is currently not supported by this repository.

**Comment by Caillen-W** [comment]
Thank you for your reply. Does this repository support the mixed precision training?

**Comment by lhoyer** [comment]
This repository is based on mmsegmentation v0.16.0, which supports mixed precision training according to its README.md (https://github.com/open-mmlab/mmsegmentation/tree/v0.16.0). However, the HRDA was not developed considering this aspect. So, you have to check if the relevant changes compared to the basic mmsegmentation framework are compatible with mixed precision training. Also, from experience with a previous project, mixed precision training can cause training instabilities and the original results might be not reproducable.
