### ISSUE TITLE
what is the difference between run_experiments.py and tools/train.py?

### ISSUE THREAD

**Issue by wzr0108** [lhoyer/HRDA#31]

**Comment by lhoyer** [comment]
run_experiments.py is a wrapper that manages the generation of the configs according to experiments.py. Also, it properly sets up the log paths.

**Comment by wzr0108** [comment]
Thank you for your answer. For model training, can tools/train.py work normally?

**Comment by lhoyer** [comment]
If you manually edit the config file according to the modifications done in `run_experiments.py`, you can also train directly with `tools/train.py`. However, to make sure that everything works as intended, I would recommend to follow the instructions in the README.md
