### ISSUE TITLE
Unknown CUDA arch or GPU not supported

### ISSUE THREAD

**Issue by MLS2021** [lhoyer/HRDA#35]
First of all, thank you for your work and your results. It's great. I encountered this problem when installing the environment:

>                     raise ValueError("Unknown CUDA arch ({}) or GPU not supported".format(arch))
>       ValueError: Unknown CUDA arch (8.9) or GPU not supported
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for mmcv-full
>   Running setup.py clean for mmcv-full
> Failed to build mmcv-full
> ERROR: Could not build wheels for mmcv-full, which is required to install pyproject.toml-based projects

This is the problem I encountered when installing mmcv-full.
My device is GTX4090. I guess it is because cuda architecture version of 4090 is not supported.
Excuse me, do you know how to solve this problem？

**Comment by lhoyer** [comment]
This seems to be a general problem of the installed CUDA version. Probably, you need to install a newer CUDA version. Alternatively, you could try to install a pre-compiled mmcv variant using `pip install mmcv-full==1.3.7 -f https://download.openmmlab.com/mmcv/dist/cu110/torch1.7/index.html`.
