### ISSUE TITLE
Operating System : Window 10 ( feat. error of Installing the mmcv-full) 

### ISSUE THREAD

**Issue by TheDarkKnight-21th** [lhoyer/HRDA#38]
Hi :) 

I have some errors for setting environments.

I already installed the cuda (toolkit) 11.0.3, torch+cu110 and torch 1.7.0.

But there is a same error with the issue (https://github.com/lhoyer/HRDA/issues/35).

My gpu is rtx 4080 and my OS is Window 10.

Can't the mmcv-full 1.3.7 be installed on Window 10?

The reason that i think like above is there are only keywords "...-manylinux1..." on https://download.openmmlab.com/mmcv/dist/cu110/torch1.7/index.html.

thank you.

**Comment by lhoyer** [comment]
The different installation variants of mmcv-full are explained here: https://github.com/open-mmlab/mmcv/tree/v1.3.7#installation. Would it work to compile mmcv-full locally by running `pip install mmcv-full==1.3.7` without providing the link for the precompiled variant?
