### ISSUE TITLE
Test Pipeline Config for Mapillary

### ISSUE THREAD

**Issue by kkaytekin** [lhoyer/HRDA#39]
Hello,
thanks for open sourcing your work. I would like to run the test script with Mapillary dataset but I am not sure which `img_scale` to use for the test pipeline, as Mapillary dataset has various image resolutions. More specifically, in the usual configs, we have `test_pipeline`s such as the one below, but I am not sure what value to give for `img_scale`. Could you maybe share the `test_pipeline` you used for Mapillary?
```
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1920, 1080),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
```
Thanks and best regards,

**Comment by lhoyer** [comment]
When testing on Mapillary, the test pipeline is modified here: https://github.com/lhoyer/HRDA/blob/70a1e8b1d4c4e8737ca286cec77b7f9a13cc32e8/tools/test.py#L228

The img_scale remains the same as for the original test pipeline.
