### ISSUE TITLE
Mixed Precision Training

### ISSUE THREAD

**Issue by Wenlve-Zhou** [lhoyer/HRDA#42]
Hello and thank you for your excellent work! I would like to ask how to use mixed precision training?

**Comment by lhoyer** [comment]
Thank you! Unfortunately, HRDA does not support mixed precision training out-of-the-box. MMSegmentation v0.16.0 seems to have support: https://github.com/open-mmlab/mmsegmentation/tree/v0.16.0/configs/fp16. However, I don't know if it will work with HRDA.
