### ISSUE TITLE
Great work! Discussion about oracle performance of GTA to Cityscapes.

### ISSUE THREAD

**Issue by xingchenzhao** [lhoyer/HRDA#6]
Thank you for your great work! 

As the paper shows, the performance of GTA to Cityscapes can achieve 73.8 mIoU which is absolutely outstanding. As HRDA is based on DAFormer structure, I checked DAFormer's oracle performance of Cityscapes which is 77.6 mIoU.  As we can see, 73.8 is just slightly lower than 77.6. Therefore, does it mean that there's no much space for us to improve GTA to Cityscapes unless we improve the oracle performance?

**Comment by lhoyer** [comment]
Hi @xingchenzhao,

Thank you for your interest in our work!

When comparing HRDA with supervised training, the high-resolution oracle (shown in Fig. 4) should be used for a more fair comparison. Therefore, there is still decent space for improvement (73.8 vs 81.2 mIoU).

Best regards,
Lukas

**Comment by xingchenzhao** [comment]
Thank you for your reply!
