### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by roessig** [lhoyer/HRDA#8]
Dear Lukas, 

are you planning to add a license to this/DAformer repo? Otherwise the code can unfortunately not be used.

**Comment by lhoyer** [comment]
We are planning to add a license to both repos. I'll let you know as soon as it is ready.

**Comment by lhoyer** [comment]
Licenses are now available for HRDA and DAFormer.

**Comment by roessig** [comment]
Thanks for the update!
